import { convertISProduct } from './convertISProduct'

const biggyProduct = {
  unitMultiplier: 1,
  year: 0,
  extraData: [
    {
      value: '1',
      key: 'sellerId',
    },
  ],
  release: 1591574400000,
  discount: 23,
  reference: '8613966',
  collections: [
    {
      id: '4550',
      position: 8,
    },
    {
      id: '4894',
      position: 65,
    },
    {
      id: '3436',
      position: 15,
    },
    {
      id: '351',
      position: 22,
    },
    {
      id: '942',
      position: 29,
    },
    {
      id: '3933',
      position: 16,
    },
    {
      id: '596',
      position: 27,
    },
  ],
  price: 7.56,
  customSort: 0,
  stickers: [
    {
      image: 'cafe-da-manha-completo',
      name: 'Café da manhã completo',
      location: 'cluster',
      target: '',
    },
  ],
  id: '6792',
  stock: 1,
  brand: 'Président',
  availableTradePolicies: ['2'],
  categoryTrees: [
    {
      categoryNames: ['Alimentos e Bebidas', 'Frios, Iogurtes e Latícinios', 'Queijos'],
      categoryIds: ['4', '1070', '3475'],
    },
    {
      categoryNames: ['Alimentos e Bebidas', 'Frios, Iogurtes e Latícinios'],
      categoryIds: ['4', '1070'],
    },
    {
      categoryNames: ['Alimentos e Bebidas'],
      categoryIds: ['4'],
    },
  ],
  images: [
    {
      name: 'queijo-mucarela-fatiado-president-150g-1.jpg',
      value:
        'https://carrefourbr.vteximg.com.br/arquivos/ids/14283089/queijo-mucarela-fatiado-president-150g-1.jpg?v=637503906472570000',
    },
  ],
  locationAttributes: [],
  tax: 0,
  productScore: 65659,
  storeSplitAttribute: '__PLACEHOLDER__',
  brandId: '2000021',
  installment: {
    interest: false,
    count: 1,
    paymentGroupName: 'creditCardPaymentGroup',
    value: 7.56,
    paymentName: 'American Express',
    valueText: 'R$ 7,56',
  },
  name: 'Queijo Muçarela Fatiado President 150g',
  boost: {
    newness: 0,
    image: 1,
    revenue: 0.058713822240958995,
    discount: 0.35384615384615387,
    productScore: 0.9969480716671728,
    click: 0.9229940764674206,
    availableSpecsCount: 0,
    promotion: 1,
    order: 0.15537190082644628,
  },
  skus: [
    {
      images: [
        {
          name: 'queijo-mucarela-fatiado-president-150g-1.jpg',
          value:
            'https://carrefourbr.vteximg.com.br/arquivos/ids/14283089/queijo-mucarela-fatiado-president-150g-1.jpg?v=637503906472570000',
        },
      ],
      nameComplete: 'Queijo Muçarela Fatiado President 150g',
      policies: [
        {
          id: '2',
          sellers: [
            {
              default: true,
              name: 'Carrefour',
              tax: 0,
              teasers: [],
              id: '1',
            },
          ],
        },
      ],
      videos: [],
      reference: '8613966',
      idWithSplit: '6793',
      ean: '7898955617526',
      name: 'Queijo Muçarela Fatiado President 150g',
      attributes: [],
      id: '6793',
      sellers: [
        {
          default: true,
          name: 'Carrefour',
          tax: 0,
          teasers: [],
          id: '1',
        },
      ],
    },
  ],
  link: 'queijo-mucarela-fatiado-president-150g-8613966',
  wear: 0,
  description:
    'Que tal dar aquele toque especial nos lanches que você preparar para a família nos finais de semana de um jeito prático, rápido e saudável? A opção mais saborosa do mercado é o Queijo Muçarela Fatiado President 150g, da Lactalis. Além da praticidade da embalagem, o produto tem como grande virtude a fórmula com base de leite de vaca pasteurizado e derivados, que dão ao alimento um sabor diferenciado, único.',
  showIfNotAvailable: true,
  clusterHighlights: {
    '4894': 'Café da manhã completo',
  },
  categories: ['Alimentos e Bebidas', 'Frios, Iogurtes e Latícinios', 'Queijos'],
  timestamp: 1619703490643,
  product: '6792',
  oldPrice: 9.79,
  productSpecifications: [
    'Description Features',
    'SAC do Fornecedor',
    'Itens Inclusos',
    'Observações',
    'Componentes Alérgicos',
    'Classificação de Origem',
    'Queijo a Base de',
    'Receita Originária',
    'Tipo de Queijo',
    'Conteúdo',
    'País',
    'Recomendações de Conservação',
    'Preferência de Consumo',
    'Fabricante',
    'SUBCATEGORIA_KEY',
    'Ingredientes',
  ],
  url: '/queijo-mucarela-fatiado-president-150g-8613966/p',
  measurementUnit: 'un',
  categoryIds: ['4', '1070', '3475'],
  textAttributes: [
    {
      joinedValue: 'president@@@Président@@@@@@president@@@Président',
      isSku: false,
      joinedKey: 'text@@@brand@@@Brand@@@brand@@@Brand',
      joinedKeyTranslations: {},
      isFilter: true,
      labelValue: 'Président',
      id: ['2000021'],
      labelKey: 'Brand',
      value: 'president',
      key: 'brand',
      joinedValueTranslations: {},
    },
    {
      valueId: '4',
      joinedValue: 'alimentos-e-bebidas@@@Alimentos e Bebidas@@@4@@@alimentos-e-bebidas@@@Alimentos e Bebidas',
      isSku: false,
      joinedKey: 'text@@@category-1@@@Category 1@@@category-1@@@Category 1',
      joinedKeyTranslations: {},
      isFilter: true,
      labelValue: 'Alimentos e Bebidas',
      id: [],
      labelKey: 'Category 1',
      value: 'alimentos-e-bebidas',
      key: 'category-1',
      joinedValueTranslations: {},
    },
    {
      valueId: '1070',
      joinedValue:
        'frios-iogurtes-e-laticinios@@@Frios, Iogurtes e Latícinios@@@1070@@@frios-iogurtes-e-laticinios@@@Frios, Iogurtes e Latícinios',
      isSku: false,
      joinedKey: 'text@@@category-2@@@Category 2@@@category-2@@@Category 2',
      joinedKeyTranslations: {},
      isFilter: true,
      labelValue: 'Frios, Iogurtes e Latícinios',
      id: [],
      labelKey: 'Category 2',
      value: 'frios-iogurtes-e-laticinios',
      key: 'category-2',
      joinedValueTranslations: {},
    },
    {
      valueId: '3475',
      joinedValue: 'queijos@@@Queijos@@@3475@@@queijos@@@Queijos',
      isSku: false,
      joinedKey: 'text@@@category-3@@@Category 3@@@category-3@@@Category 3',
      joinedKeyTranslations: {},
      isFilter: true,
      labelValue: 'Queijos',
      id: [],
      labelKey: 'Category 3',
      value: 'queijos',
      key: 'category-3',
      joinedValueTranslations: {},
    },
    {
      joinedValue: '351@@@351@@@@@@351@@@351',
      isSku: false,
      joinedKey: 'text@@@productclusterids@@@productClusterIds@@@productclusterids@@@productClusterIds',
      joinedKeyTranslations: {},
      isFilter: false,
      labelValue: '351',
      id: [],
      labelKey: 'productClusterIds',
      value: '351',
      key: 'productclusterids',
      joinedValueTranslations: {},
    },
    {
      joinedValue: '596@@@596@@@@@@596@@@596',
      isSku: false,
      joinedKey: 'text@@@productclusterids@@@productClusterIds@@@productclusterids@@@productClusterIds',
      joinedKeyTranslations: {},
      isFilter: false,
      labelValue: '596',
      id: [],
      labelKey: 'productClusterIds',
      value: '596',
      key: 'productclusterids',
      joinedValueTranslations: {},
    },
    {
      joinedValue: '942@@@942@@@@@@942@@@942',
      isSku: false,
      joinedKey: 'text@@@productclusterids@@@productClusterIds@@@productclusterids@@@productClusterIds',
      joinedKeyTranslations: {},
      isFilter: false,
      labelValue: '942',
      id: [],
      labelKey: 'productClusterIds',
      value: '942',
      key: 'productclusterids',
      joinedValueTranslations: {},
    },
    {
      joinedValue: '3436@@@3436@@@@@@3436@@@3436',
      isSku: false,
      joinedKey: 'text@@@productclusterids@@@productClusterIds@@@productclusterids@@@productClusterIds',
      joinedKeyTranslations: {},
      isFilter: false,
      labelValue: '3436',
      id: [],
      labelKey: 'productClusterIds',
      value: '3436',
      key: 'productclusterids',
      joinedValueTranslations: {},
    },
    {
      joinedValue: '3933@@@3933@@@@@@3933@@@3933',
      isSku: false,
      joinedKey: 'text@@@productclusterids@@@productClusterIds@@@productclusterids@@@productClusterIds',
      joinedKeyTranslations: {},
      isFilter: false,
      labelValue: '3933',
      id: [],
      labelKey: 'productClusterIds',
      value: '3933',
      key: 'productclusterids',
      joinedValueTranslations: {},
    },
    {
      joinedValue: '4550@@@4550@@@@@@4550@@@4550',
      isSku: false,
      joinedKey: 'text@@@productclusterids@@@productClusterIds@@@productclusterids@@@productClusterIds',
      joinedKeyTranslations: {},
      isFilter: false,
      labelValue: '4550',
      id: [],
      labelKey: 'productClusterIds',
      value: '4550',
      key: 'productclusterids',
      joinedValueTranslations: {},
    },
    {
      joinedValue: '4894@@@4894@@@@@@4894@@@4894',
      isSku: false,
      joinedKey: 'text@@@productclusterids@@@productClusterIds@@@productclusterids@@@productClusterIds',
      joinedKeyTranslations: {},
      isFilter: false,
      labelValue: '4894',
      id: [],
      labelKey: 'productClusterIds',
      value: '4894',
      key: 'productclusterids',
      joinedValueTranslations: {},
    },
    {
      valueId: '351',
      joinedValue: 'monte-seu-lanche@@@Monte seu Lanche@@@351@@@monte-seu-lanche@@@Monte seu Lanche',
      isSku: false,
      joinedKey: 'text@@@productclusternames@@@productClusterNames@@@productclusternames@@@productClusterNames',
      joinedKeyTranslations: {},
      isFilter: false,
      labelValue: 'Monte seu Lanche',
      id: [],
      labelKey: 'productClusterNames',
      value: 'monte-seu-lanche',
      key: 'productclusternames',
      joinedValueTranslations: {},
    },
    {
      valueId: '596',
      joinedValue:
        'selecao-cafe-da-manha@@@Seleção Café da Manhã@@@596@@@selecao-cafe-da-manha@@@Seleção Café da Manhã',
      isSku: false,
      joinedKey: 'text@@@productclusternames@@@productClusterNames@@@productclusternames@@@productClusterNames',
      joinedKeyTranslations: {},
      isFilter: false,
      labelValue: 'Seleção Café da Manhã',
      id: [],
      labelKey: 'productClusterNames',
      value: 'selecao-cafe-da-manha',
      key: 'productclusternames',
      joinedValueTranslations: {},
    },
    {
      valueId: '942',
      joinedValue: 'petiscos-@@@Petiscos @@@942@@@petiscos-@@@Petiscos ',
      isSku: false,
      joinedKey: 'text@@@productclusternames@@@productClusterNames@@@productclusternames@@@productClusterNames',
      joinedKeyTranslations: {},
      isFilter: false,
      labelValue: 'Petiscos ',
      id: [],
      labelKey: 'productClusterNames',
      value: 'petiscos-',
      key: 'productclusternames',
      joinedValueTranslations: {},
    },
    {
      valueId: '3436',
      joinedValue: 'queijos-@@@Queijos @@@3436@@@queijos-@@@Queijos ',
      isSku: false,
      joinedKey: 'text@@@productclusternames@@@productClusterNames@@@productclusternames@@@productClusterNames',
      joinedKeyTranslations: {},
      isFilter: false,
      labelValue: 'Queijos ',
      id: [],
      labelKey: 'productClusterNames',
      value: 'queijos-',
      key: 'productclusternames',
      joinedValueTranslations: {},
    },
    {
      valueId: '3933',
      joinedValue:
        'food-15-porcento-nao-excluir@@@food-15-porcento-NAO-EXCLUIR@@@3933@@@food-15-porcento-nao-excluir@@@food-15-porcento-NAO-EXCLUIR',
      isSku: false,
      joinedKey: 'text@@@productclusternames@@@productClusterNames@@@productclusternames@@@productClusterNames',
      joinedKeyTranslations: {},
      isFilter: false,
      labelValue: 'food-15-porcento-NAO-EXCLUIR',
      id: [],
      labelKey: 'productClusterNames',
      value: 'food-15-porcento-nao-excluir',
      key: 'productclusternames',
      joinedValueTranslations: {},
    },
    {
      valueId: '4550',
      joinedValue:
        'frios-e-queijos-a-partir-r--299@@@FRIOS E QUEIJOS A PARTIR R$ 2,99@@@4550@@@frios-e-queijos-a-partir-r--299@@@FRIOS E QUEIJOS A PARTIR R$ 2,99',
      isSku: false,
      joinedKey: 'text@@@productclusternames@@@productClusterNames@@@productclusternames@@@productClusterNames',
      joinedKeyTranslations: {},
      isFilter: false,
      labelValue: 'FRIOS E QUEIJOS A PARTIR R$ 2,99',
      id: [],
      labelKey: 'productClusterNames',
      value: 'frios-e-queijos-a-partir-r--299',
      key: 'productclusternames',
      joinedValueTranslations: {},
    },
    {
      valueId: '4894',
      joinedValue:
        'cafe-da-manha-completo@@@Café da manhã completo@@@4894@@@cafe-da-manha-completo@@@Café da manhã completo',
      isSku: false,
      joinedKey: 'text@@@productclusternames@@@productClusterNames@@@productclusternames@@@productClusterNames',
      joinedKeyTranslations: {},
      isFilter: false,
      labelValue: 'Café da manhã completo',
      id: [],
      labelKey: 'productClusterNames',
      value: 'cafe-da-manha-completo',
      key: 'productclusternames',
      joinedValueTranslations: {},
    },
    {
      joinedValue: 'false@@@false@@@@@@false@@@false',
      isSku: false,
      joinedKey: 'text@@@subscription@@@subscription@@@subscription@@@subscription',
      joinedKeyTranslations: {},
      isFilter: false,
      labelValue: 'false',
      id: [],
      labelKey: 'subscription',
      value: 'false',
      key: 'subscription',
      joinedValueTranslations: {},
    },
    {
      joinedValue: '2@@@2@@@@@@2@@@2',
      isSku: false,
      joinedKey: 'text@@@trade-policy@@@Trade Policy@@@trade-policy@@@Trade Policy',
      joinedKeyTranslations: {},
      isFilter: false,
      labelValue: '2',
      id: [],
      labelKey: 'Trade Policy',
      value: '2',
      key: 'trade-policy',
      joinedValueTranslations: {},
    },
    {
      joinedValue: '3@@@3@@@@@@3@@@3',
      isSku: false,
      joinedKey: 'text@@@trade-policy@@@Trade Policy@@@trade-policy@@@Trade Policy',
      joinedKeyTranslations: {},
      isFilter: false,
      labelValue: '3',
      id: [],
      labelKey: 'Trade Policy',
      value: '3',
      key: 'trade-policy',
      joinedValueTranslations: {},
    },
    {
      joinedValue: '5@@@5@@@@@@5@@@5',
      isSku: false,
      joinedKey: 'text@@@trade-policy@@@Trade Policy@@@trade-policy@@@Trade Policy',
      joinedKeyTranslations: {},
      isFilter: false,
      labelValue: '5',
      id: [],
      labelKey: 'Trade Policy',
      value: '5',
      key: 'trade-policy',
      joinedValueTranslations: {},
    },
    {
      joinedValue: '7@@@7@@@@@@7@@@7',
      isSku: false,
      joinedKey: 'text@@@trade-policy@@@Trade Policy@@@trade-policy@@@Trade Policy',
      joinedKeyTranslations: {},
      isFilter: false,
      labelValue: '7',
      id: [],
      labelKey: 'Trade Policy',
      value: '7',
      key: 'trade-policy',
      joinedValueTranslations: {},
    },
    {
      joinedValue: '1@@@1@@@@@@1@@@1',
      isSku: false,
      joinedKey: 'text@@@seller@@@Seller@@@seller@@@Seller',
      joinedKeyTranslations: {},
      isFilter: false,
      labelValue: '1',
      id: [],
      labelKey: 'Seller',
      value: '1',
      key: 'seller',
      joinedValueTranslations: {},
    },
    {
      valueId: '1',
      joinedValue: 'carrefour@@@Carrefour@@@1@@@carrefour@@@Carrefour',
      isSku: false,
      joinedKey: 'text@@@sellername@@@sellerName@@@sellername@@@sellerName',
      joinedKeyTranslations: {},
      isFilter: false,
      labelValue: 'Carrefour',
      id: [],
      labelKey: 'sellerName',
      value: 'carrefour',
      key: 'sellername',
      joinedValueTranslations: {},
    },
    {
      joinedValue:
        'produto-fatiado--nao-contem-gluten--consevar-fechado-em-local-fresco--queijo-mucarela-president-150-g@@@Produto fatiado; Não contém glúten; Consevar fechado em local fresco; Queijo Muçarela President 150 g@@@@@@produto-fatiado--nao-contem-gluten--consevar-fechado-em-local-fresco--queijo-mucarela-president-150-g@@@Produto fatiado; Não contém glúten; Consevar fechado em local fresco; Queijo Muçarela President 150 g',
      isSku: false,
      joinedKey: 'text@@@description-features@@@Description Features@@@description-features@@@Description Features',
      joinedKeyTranslations: {},
      isFilter: false,
      labelValue:
        'Produto fatiado; Não contém glúten; Consevar fechado em local fresco; Queijo Muçarela President 150 g',
      id: ['28993'],
      labelKey: 'Description Features',
      value: 'produto-fatiado--nao-contem-gluten--consevar-fechado-em-local-fresco--queijo-mucarela-president-150-g',
      key: 'description-features',
      joinedValueTranslations: {},
    },
    {
      joinedValue:
        '0800-512-198-sac-lactalisdobrasil-com-br@@@0800 512 198, sac@lactalisdobrasil.com.br@@@@@@0800-512-198-sac-lactalisdobrasil-com-br@@@0800 512 198, sac@lactalisdobrasil.com.br',
      isSku: false,
      joinedKey: 'text@@@sac-do-fornecedor@@@SAC do Fornecedor@@@sac-do-fornecedor@@@SAC do Fornecedor',
      joinedKeyTranslations: {},
      isFilter: false,
      labelValue: '0800 512 198, sac@lactalisdobrasil.com.br',
      id: ['35'],
      labelKey: 'SAC do Fornecedor',
      value: '0800-512-198-sac-lactalisdobrasil-com-br',
      key: 'sac-do-fornecedor',
      joinedValueTranslations: {},
    },
    {
      joinedValue:
        '1-bandeja-de-queijo-mucarela-fatiado-president-150g@@@1 Bandeja de Queijo Muçarela Fatiado President 150g@@@@@@1-bandeja-de-queijo-mucarela-fatiado-president-150g@@@1 Bandeja de Queijo Muçarela Fatiado President 150g',
      isSku: false,
      joinedKey: 'text@@@itens-inclusos@@@Itens Inclusos@@@itens-inclusos@@@Itens Inclusos',
      joinedKeyTranslations: {},
      isFilter: false,
      labelValue: '1 Bandeja de Queijo Muçarela Fatiado President 150g',
      id: ['36'],
      labelKey: 'Itens Inclusos',
      value: '1-bandeja-de-queijo-mucarela-fatiado-president-150g',
      key: 'itens-inclusos',
      joinedValueTranslations: {},
    },
    {
      joinedValue:
        'imagem-meramente-ilustrativa-prazo-de-validade--vide-impresso-na-embalagem-@@@Imagem meramente ilustrativa\nPrazo de Validade: Vide Impresso na Embalagem.@@@@@@imagem-meramente-ilustrativa-prazo-de-validade--vide-impresso-na-embalagem-@@@Imagem meramente ilustrativa\nPrazo de Validade: Vide Impresso na Embalagem.',
      isSku: false,
      joinedKey: 'text@@@observacoes@@@Observações@@@observacoes@@@Observações',
      joinedKeyTranslations: {},
      isFilter: false,
      labelValue: 'Imagem meramente ilustrativa\nPrazo de Validade: Vide Impresso na Embalagem.',
      id: ['38'],
      labelKey: 'Observações',
      value: 'imagem-meramente-ilustrativa-prazo-de-validade--vide-impresso-na-embalagem-',
      key: 'observacoes',
      joinedValueTranslations: {},
    },
    {
      joinedValue:
        'contem-leite-e-derivados-@@@Contém Leite e Derivados.@@@@@@contem-leite-e-derivados-@@@Contém Leite e Derivados.',
      isSku: false,
      joinedKey: 'text@@@componentes-alergicos@@@Componentes Alérgicos@@@componentes-alergicos@@@Componentes Alérgicos',
      joinedKeyTranslations: {},
      isFilter: false,
      labelValue: 'Contém Leite e Derivados.',
      id: ['126'],
      labelKey: 'Componentes Alérgicos',
      value: 'contem-leite-e-derivados-',
      key: 'componentes-alergicos',
      joinedValueTranslations: {},
    },
    {
      valueId: '485',
      joinedValue: 'original@@@Original@@@485@@@original@@@Original',
      isSku: false,
      joinedKey:
        'text@@@classificacao-de-origem@@@Classificação de Origem@@@classificacao-de-origem@@@Classificação de Origem',
      joinedKeyTranslations: {},
      isFilter: false,
      labelValue: 'Original',
      id: ['634'],
      labelKey: 'Classificação de Origem',
      value: 'original',
      key: 'classificacao-de-origem',
      joinedValueTranslations: {},
    },
    {
      valueId: '492',
      joinedValue: 'leite-de-vaca@@@Leite de Vaca@@@492@@@leite-de-vaca@@@Leite de Vaca',
      isSku: false,
      joinedKey: 'text@@@queijo-a-base-de@@@Queijo a Base de@@@queijo-a-base-de@@@Queijo a Base de',
      joinedKeyTranslations: {},
      isFilter: false,
      labelValue: 'Leite de Vaca',
      id: ['636'],
      labelKey: 'Queijo a Base de',
      value: 'leite-de-vaca',
      key: 'queijo-a-base-de',
      joinedValueTranslations: {},
    },
    {
      valueId: '1111',
      joinedValue: 'brasil@@@Brasil@@@1111@@@brasil@@@Brasil',
      isSku: false,
      joinedKey: 'text@@@receita-originaria@@@Receita Originária@@@receita-originaria@@@Receita Originária',
      joinedKeyTranslations: {},
      isFilter: false,
      labelValue: 'Brasil',
      id: ['637'],
      labelKey: 'Receita Originária',
      value: 'brasil',
      key: 'receita-originaria',
      joinedValueTranslations: {},
    },
    {
      valueId: '5346',
      joinedValue: 'mussarela@@@Mussarela@@@5346@@@mussarela@@@Mussarela',
      isSku: false,
      joinedKey: 'text@@@tipo-de-queijo@@@Tipo de Queijo@@@tipo-de-queijo@@@Tipo de Queijo',
      joinedKeyTranslations: {},
      isFilter: true,
      labelValue: 'Mussarela',
      id: ['643'],
      labelKey: 'Tipo de Queijo',
      value: 'mussarela',
      key: 'tipo-de-queijo',
      joinedValueTranslations: {},
    },
    {
      valueId: '122304',
      joinedValue: '150-g@@@150 g@@@122304@@@150-g@@@150 g',
      isSku: false,
      joinedKey: 'text@@@conteudo@@@Conteúdo@@@conteudo@@@Conteúdo',
      joinedKeyTranslations: {},
      isFilter: true,
      labelValue: '150 g',
      id: ['128'],
      labelKey: 'Conteúdo',
      value: '150-g',
      key: 'conteudo',
      joinedValueTranslations: {},
    },
    {
      valueId: '450',
      joinedValue: 'brasil@@@Brasil@@@450@@@brasil@@@Brasil',
      isSku: false,
      joinedKey: 'text@@@pais@@@País@@@pais@@@País',
      joinedKeyTranslations: {},
      isFilter: false,
      labelValue: 'Brasil',
      id: ['140'],
      labelKey: 'País',
      value: 'brasil',
      key: 'pais',
      joinedValueTranslations: {},
    },
    {
      joinedValue:
        'manter-a-embalagem-bem-fechada-em-lugar-fresco-@@@Manter a Embalagem Bem Fechada em Lugar Fresco.@@@@@@manter-a-embalagem-bem-fechada-em-lugar-fresco-@@@Manter a Embalagem Bem Fechada em Lugar Fresco.',
      isSku: false,
      joinedKey:
        'text@@@recomendacoes-de-conservacao@@@Recomendações de Conservação@@@recomendacoes-de-conservacao@@@Recomendações de Conservação',
      joinedKeyTranslations: {},
      isFilter: false,
      labelValue: 'Manter a Embalagem Bem Fechada em Lugar Fresco.',
      id: ['141'],
      labelKey: 'Recomendações de Conservação',
      value: 'manter-a-embalagem-bem-fechada-em-lugar-fresco-',
      key: 'recomendacoes-de-conservacao',
      joinedValueTranslations: {},
    },
    {
      valueId: '467',
      joinedValue: 'nao-contem-gluten@@@Não Contém Glúten@@@467@@@nao-contem-gluten@@@Não Contém Glúten',
      isSku: false,
      joinedKey:
        'text@@@preferencia-de-consumo@@@Preferência de Consumo@@@preferencia-de-consumo@@@Preferência de Consumo',
      joinedKeyTranslations: {},
      isFilter: true,
      labelValue: 'Não Contém Glúten',
      id: ['133'],
      labelKey: 'Preferência de Consumo',
      value: 'nao-contem-gluten',
      key: 'preferencia-de-consumo',
      joinedValueTranslations: {},
    },
    {
      valueId: '489',
      joinedValue: 'lactalis@@@Lactalis@@@489@@@lactalis@@@Lactalis',
      isSku: false,
      joinedKey: 'text@@@fabricante@@@Fabricante@@@fabricante@@@Fabricante',
      joinedKeyTranslations: {},
      isFilter: false,
      labelValue: 'Lactalis',
      id: ['134'],
      labelKey: 'Fabricante',
      value: 'lactalis',
      key: 'fabricante',
      joinedValueTranslations: {},
    },
    {
      joinedValue: '92020420109@@@92020420109@@@@@@92020420109@@@92020420109',
      isSku: false,
      joinedKey: 'text@@@subcategoria-key@@@SUBCATEGORIA_KEY@@@subcategoria-key@@@SUBCATEGORIA_KEY',
      joinedKeyTranslations: {},
      isFilter: false,
      labelValue: '92020420109',
      id: ['28079'],
      labelKey: 'SUBCATEGORIA_KEY',
      value: '92020420109',
      key: 'subcategoria-key',
      joinedValueTranslations: {},
    },
    {
      joinedValue:
        'leite-pasteurizado-cloreto-de-sodio--sal--cloreto-de-calcio-coalho-fermento-lacteo-e-conservador-natamicina--uso-externo--@@@Leite Pasteurizado, Cloreto de Sódio (Sal), Cloreto de Cálcio, Coalho, Fermento Lácteo e Conservador Natamicina (Uso Externo).@@@@@@leite-pasteurizado-cloreto-de-sodio--sal--cloreto-de-calcio-coalho-fermento-lacteo-e-conservador-natamicina--uso-externo--@@@Leite Pasteurizado, Cloreto de Sódio (Sal), Cloreto de Cálcio, Coalho, Fermento Lácteo e Conservador Natamicina (Uso Externo).',
      isSku: false,
      joinedKey: 'text@@@ingredientes@@@Ingredientes@@@ingredientes@@@Ingredientes',
      joinedKeyTranslations: {},
      isFilter: false,
      labelValue:
        'Leite Pasteurizado, Cloreto de Sódio (Sal), Cloreto de Cálcio, Coalho, Fermento Lácteo e Conservador Natamicina (Uso Externo).',
      id: ['135'],
      labelKey: 'Ingredientes',
      value:
        'leite-pasteurizado-cloreto-de-sodio--sal--cloreto-de-calcio-coalho-fermento-lacteo-e-conservador-natamicina--uso-externo--',
      key: 'ingredientes',
      joinedValueTranslations: {},
    },
    {
      joinedValue: 'yes@@@Yes@@@@@@yes@@@Yes',
      isSku: false,
      joinedKey: 'text@@@promotion@@@Promotion@@@promotion@@@Promotion',
      joinedKeyTranslations: {},
      isFilter: true,
      labelValue: 'Yes',
      id: [],
      labelKey: 'Promotion',
      value: 'yes',
      key: 'promotion',
      joinedValueTranslations: {},
    },
  ],
  numberAttributes: [
    {
      labelKey: 'Price',
      value: 7.56,
      key: 'price',
    },
  ],
  headSku: '6793',
  specificationGroups:
    '{"Categoria de Gestão":["SUBCATEGORIA_KEY"],"Importante":["SAC do Fornecedor","Itens Inclusos","Observações"],"Informações Nutricionais":["Ingredientes"],"Descrição":["Description Features"],"Informações do Produto":["Componentes Alérgicos","Classificação de Origem","Queijo a Base de","Receita Originária","Tipo de Queijo","Conteúdo","País","Recomendações de Conservação","Preferência de Consumo","Fabricante"]}',
  extraInfo: {
    sellerId: '1',
  },
  oldPriceText: 'R$ 9,79',
  priceText: 'R$ 7,56',
}

const vtexProduct = convertISProduct(biggyProduct as any)

console.log(JSON.stringify(vtexProduct))
